import {
  UserProfile,
  ApplicationRecord,
  UploadedDocument,
  ApplicationTemplate,
  ChatMessage,
  GovNotice,
} from './types';

export const NATIONAL_PORTAL_HELPLINE = '1800-115-555 (Toll Free) / 1947 (Aadhaar UIDAI)';
export const IT_ACT_COMPLIANCE_NOTICE =
  'Statutory e-Filing Portal under the Information Technology Act, 2000 (Section 65B Electronic Records). All DigiLocker fetched credentials are legally recognized equivalent to original physical documents under Rule 9A of IT Rules 2016.';
export const ENCRYPTION_STANDARD_LABEL = 'DigiLocker 256-bit AES-GCM (Cert-In Empanelled)';
export const MAX_FILE_SIZE_BYTES = 25 * 1024 * 1024; // 25 MB

export const DEFAULT_USER_PROFILE: UserProfile = {
  id: 'usr-digilocker-8849',
  name: 'Shivang Khorjuvekar',
  hindiName: 'शिवांग खोर्जुवेकर',
  email: 'khorjuvekarshivang@gmail.com',
  aadhaarMasked: 'XXXX-XXXX-8421',
  panNumber: 'ABCDE1234F',
  phone: '+91 98201 55492',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  assuranceLevel: 'MeriPehchaan (Level 3 - Aadhaar e-KYC)',
  authMethod: 'MeriPehchaan NSSO',
  sessionTokenHash: 'sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
  storageUsedBytes: 4.8 * 1024 * 1024,
  storageQuotaBytes: 1024 * 1024 * 1024, // 1 GB DigiLocker quota
  provider: 'MeriPehchaan (National SSO)',
  is2FAEnabled: true,
  stateOrUT: 'Maharashtra',
  cityOrDistrict: 'Pune',
  primaryAddress: 'Flat 402, Shiv Shristi Enclave, Baner Road',
  pincode: '411045',
  dateOfBirth: '1995-11-20',
  gender: 'Male',
  occupation: 'Founder & CTO (Apex Cybernetics)',
  digiLockerDocCount: 4,
};

export const DEMO_CITIZEN_PROFILES: UserProfile[] = [
  DEFAULT_USER_PROFILE,
  {
    id: 'usr-digilocker-9921',
    name: 'Dr. Ananya Sharma',
    hindiName: 'डॉ. अनन्या शर्मा',
    email: 'ananya.sharma.dst@gov.res.in',
    aadhaarMasked: 'XXXX-XXXX-3190',
    panNumber: 'ANASP4821M',
    phone: '+91 98110 44219',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    assuranceLevel: 'MeriPehchaan (Level 3 - Aadhaar e-KYC)',
    authMethod: 'MeriPehchaan NSSO',
    sessionTokenHash: 'sha256:3a91b2c45d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a',
    storageUsedBytes: 2.3 * 1024 * 1024,
    storageQuotaBytes: 1024 * 1024 * 1024,
    provider: 'MeriPehchaan (National SSO)',
    is2FAEnabled: true,
    stateOrUT: 'Delhi (NCT)',
    cityOrDistrict: 'New Delhi',
    primaryAddress: 'C-4/18, Hauz Khas Enclave',
    pincode: '110016',
    dateOfBirth: '1992-04-14',
    gender: 'Female',
    occupation: 'Postdoctoral Research Scientist (DST Fellow)',
    digiLockerDocCount: 3,
  },
  {
    id: 'usr-digilocker-7740',
    name: 'Ramesh Patel',
    hindiName: 'रमेश पटेल',
    email: 'ramesh.patel.msme@gmail.com',
    aadhaarMasked: 'XXXX-XXXX-9902',
    panNumber: 'RPATL7732K',
    phone: '+91 94260 11893',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    assuranceLevel: 'MeriPehchaan (Level 3 - Aadhaar e-KYC)',
    authMethod: 'DigiLocker OAuth 2.0',
    sessionTokenHash: 'sha256:8b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c',
    storageUsedBytes: 6.1 * 1024 * 1024,
    storageQuotaBytes: 1024 * 1024 * 1024,
    provider: 'DigiLocker',
    is2FAEnabled: true,
    stateOrUT: 'Gujarat',
    cityOrDistrict: 'Ahmedabad',
    primaryAddress: 'Plot 48, GIDC Industrial Estate, Vatva',
    pincode: '382445',
    dateOfBirth: '1984-08-05',
    gender: 'Male',
    occupation: 'Managing Director (Patel Precision Works)',
    digiLockerDocCount: 5,
  },
  {
    id: 'usr-digilocker-5512',
    name: 'Kavita Devi',
    hindiName: 'कविता देवी',
    email: 'kavita.devi.shg@gmail.com',
    aadhaarMasked: 'XXXX-XXXX-6614',
    panNumber: 'KDVIR9912E',
    phone: '+91 94500 88214',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    assuranceLevel: 'MeriPehchaan (Level 3 - Aadhaar e-KYC)',
    authMethod: 'Aadhaar OTP',
    sessionTokenHash: 'sha256:9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d',
    storageUsedBytes: 1.1 * 1024 * 1024,
    storageQuotaBytes: 1024 * 1024 * 1024,
    provider: 'MeriPehchaan (National SSO)',
    is2FAEnabled: true,
    stateOrUT: 'Uttar Pradesh',
    cityOrDistrict: 'Varanasi',
    primaryAddress: 'Village Shivpur, Block Harhua',
    pincode: '221003',
    dateOfBirth: '1990-03-22',
    gender: 'Female',
    occupation: 'Handloom Artisan & SHG Leader (PMEGP)',
    digiLockerDocCount: 2,
  },
];

export const GOVERNMENT_NOTICES: GovNotice[] = [
  {
    id: 'notif-01',
    type: 'info',
    title: 'DPIIT Startup India Seed Fund FY 2026-27 Applications Open',
    titleHindi: 'स्टार्टअप इंडिया सीड फंड योजना (SISFS) 2026 आवेदन खुले हैं',
    description:
      'Eligible recognized startups can apply for up to ₹25 Lakhs proof-of-concept grant. DigiLocker authenticated Aadhaar and DPIIT recognition certificate required.',
    date: '18 Aug 2026',
  },
  {
    id: 'notif-02',
    type: 'deadline',
    title: 'DST INSPIRE Faculty Fellowship: Submission Closes Nov 30',
    titleHindi: 'डीएसटी इंस्पायर फैकल्टी फेलोशिप अंतिम तिथि 30 नवंबर',
    description:
      'Doctoral degree holders under 32 years can apply for senior contractual research fellowship with ₹35 Lakhs laboratory grant.',
    date: '15 Aug 2026',
  },
  {
    id: 'notif-03',
    type: 'warning',
    title: 'Mandatory Aadhaar-PAN Linking for Subsidized DBT Claims',
    titleHindi: 'प्रत्यक्ष लाभ हस्तांतरण (DBT) के लिए आधार-पैन लिंकिंग अनिवार्य',
    description:
      'Under Ministry of Finance guidelines, ensure Aadhaar is seeded with NPCI mapper for instant direct benefit transfer to bank account.',
    date: '10 Aug 2026',
  },
];

export const DEFAULT_APPLICATION_TEMPLATES: ApplicationTemplate[] = [
  {
    id: 'tmpl-sisfs-grant',
    title: 'DPIIT Startup India Seed Fund Scheme (SISFS)',
    name: 'DPIIT Startup India Seed Fund Scheme (SISFS)',
    category: 'Startup & MSME Grant',
    ministryName: 'Ministry of Commerce and Industry',
    departmentName: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    schemeCode: 'DPIIT/SISFS/2026/G-424',
    description:
      'Financial assistance to innovative startups for proof of concept, prototype development, product trials, market entry, and commercialization.',
    requiredDocTypes: ['Aadhaar Card (UIDAI)', 'Income Tax PAN Card', 'ITR-V / Balance Sheet', 'DPIIT Certificate of Recognition'],
    requiredEvidenceList: ['Aadhaar e-KYC', 'PAN Card (NSDL)', 'ITR-V Tax Return', 'Udyam / DPIIT Certificate'],
    estimatedProcessingTime: '21 Working Days',
    statutoryDeadline: '15 Nov 2026',
    defaultAmount: '₹25,00,000 (Twenty Five Lakhs INR)',
    defaultFundingAmount: '₹25,00,000 (Twenty Five Lakhs INR)',
    defaultFormData: {
      schemeOrCategory: 'Early Stage Deep-Tech & AI Startup Prototype Acceleration',
      requestedGrantOrSubsidy: '₹25,00,000 INR (Grant & Convertible Debenture)',
      purposeStatement:
        'Development of high-throughput automated digital citizen identity validation engines and cloud-native cryptographic verifiable credential infrastructures under Make in India.',
    },
  },
  {
    id: 'tmpl-dst-inspire',
    title: 'DST INSPIRE Senior Research Faculty Fellowship',
    name: 'DST INSPIRE Senior Research Faculty Fellowship',
    category: 'Academic & Research Fellowship',
    ministryName: 'Ministry of Science and Technology',
    departmentName: 'Department of Science & Technology (DST)',
    schemeCode: 'DST/INSPIRE/2026/F-101',
    description:
      'Prestigious research fellowship providing independent faculty positions and research support for postdoctoral scientists to conduct cutting-edge research in Indian institutions.',
    requiredDocTypes: ['Aadhaar Card (UIDAI)', 'Doctorate Degree Transcript', 'Institutional Endorsement Letter'],
    requiredEvidenceList: ['Aadhaar Card', 'NAD Academic Degree', 'PAN Card'],
    estimatedProcessingTime: '45 Working Days',
    statutoryDeadline: '30 Nov 2026',
    defaultAmount: '₹35,00,000 (Thirty Five Lakhs INR)',
    defaultFundingAmount: '₹35,00,000 (Thirty Five Lakhs INR)',
    defaultFormData: {
      schemeOrCategory: 'Advanced Computing & Cryptographic Systems Fellowship',
      requestedGrantOrSubsidy: '₹35,00,000 Research Grant + ₹1,25,000/mo Fellowship',
      purposeStatement:
        'Investigating quantum-resistant public key infrastructure and scalable distributed ledger models for sovereign digital governance systems.',
    },
  },
  {
    id: 'tmpl-pmegp-subsidy',
    title: 'Prime Minister Employment Generation Programme (PMEGP)',
    name: 'Prime Minister Employment Generation Programme (PMEGP)',
    category: 'Employment & Skill Development',
    ministryName: 'Ministry of Micro, Small & Medium Enterprises',
    departmentName: 'Khadi and Village Industries Commission (KVIC)',
    schemeCode: 'MSME/PMEGP/2026/S-88',
    description:
      'Credit-linked subsidy programme to generate self-employment opportunities through establishment of micro-enterprises in non-farm sectors.',
    requiredDocTypes: ['Aadhaar Card (UIDAI)', 'PAN Card', 'EDP Training Certificate', 'Detailed Project Report (DPR)'],
    requiredEvidenceList: ['Aadhaar Card', 'PAN Card', 'Bank Passbook', 'Project Report'],
    estimatedProcessingTime: '15 Working Days',
    statutoryDeadline: '31 Dec 2026',
    defaultAmount: '₹50,00,000 Project Capital (35% Margin Subsidy)',
    defaultFundingAmount: '₹50,00,000 Project Capital (35% Margin Subsidy)',
    defaultFormData: {
      schemeOrCategory: 'Manufacturing & Tech-Enabled Enterprise Unit',
      requestedGrantOrSubsidy: '₹50,00,000 Project Outlay (₹17,50,000 Govt Subsidy)',
      purposeStatement:
        'Establishing a specialized high-security digital hardware manufacturing unit with localized component sourcing and employment generation for 18 personnel.',
    },
  },
  {
    id: 'tmpl-msme-udyam',
    title: 'MSME Udyam Enterprise Certification & Trade License',
    name: 'MSME Udyam Enterprise Certification & Trade License',
    category: 'Trade & Industrial License',
    ministryName: 'Ministry of Micro, Small & Medium Enterprises',
    departmentName: 'Udyam Registration Portal Directorate',
    schemeCode: 'MSME/UDYAM/2026/REG-99',
    description:
      'Statutory permanent identity number and electronic registration certificate for micro, small, and medium enterprises with priority sector bank lending eligibility.',
    requiredDocTypes: ['Aadhaar Card', 'PAN Card', 'GSTIN Certificate'],
    requiredEvidenceList: ['Aadhaar Card', 'PAN Card', 'Bank Account Proof'],
    estimatedProcessingTime: 'Instant (1-2 Days)',
    statutoryDeadline: 'Continuous Scheme',
    defaultAmount: 'Statutory Zero Fee (Free National Registration)',
    defaultFundingAmount: 'Statutory Zero Fee (Free National Registration)',
    defaultFormData: {
      schemeOrCategory: 'Micro Enterprise - Computer Programming & Advisory',
      requestedGrantOrSubsidy: 'Statutory Registration & Priority Bank Credit Access',
      purposeStatement:
        'Official formalization and registration under the MSMED Act, 2006 for enterprise expansion and government e-Marketplace (GeM) tender participation.',
    },
  },
];

export const DEFAULT_DOCUMENTS: UploadedDocument[] = [
  {
    id: 'doc-aadhaar-01',
    name: 'Aadhaar_Card_UIDAI_Verified.pdf',
    originalName: 'Aadhaar_Card_UIDAI_Verified.pdf',
    fileType: 'application/pdf',
    size: 1458900,
    uploadDate: '12 Aug 2026, 10:14 IST',
    isEncrypted: true,
    encryptionAlgorithm: 'AES-256-GCM',
    sha256Hash: '9f83c14298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    docType: 'Aadhaar Card (UIDAI Verified)',
    confidenceScore: 99.8,
    verificationStatus: 'verified',
    digiLockerIssuer: 'Unique Identification Authority of India (UIDAI)',
    itActSection65BVerified: true,
    summary:
      'Official DigiLocker-pulled digital Aadhaar with QR code and cryptographic signature from UIDAI. Domicile and biometric verification certified.',
    extractedFields: {
      fullName: 'Shivang Khorjuvekar',
      dob: '1995-11-20',
      idNumber: 'XXXX-XXXX-8421',
      fatherOrSpouseName: 'Ramesh Khorjuvekar',
      address: 'Flat 402, Shiv Shristi Enclave, Baner Road, Pune, Maharashtra 411045',
    },
    securityVerification: {
      tamperDetected: false,
      readableQuality: 'High',
      notes: 'DigiLocker PKI e-Sign validated against UIDAI Public Root Certificate.',
    },
  },
  {
    id: 'doc-pan-02',
    name: 'Income_Tax_PAN_Card_NSDL.pdf',
    originalName: 'Income_Tax_PAN_Card_NSDL.pdf',
    fileType: 'application/pdf',
    size: 984500,
    uploadDate: '12 Aug 2026, 10:16 IST',
    isEncrypted: true,
    encryptionAlgorithm: 'AES-256-GCM',
    sha256Hash: '4a6b2c89f412e6501a3b8c7e9d0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f',
    docType: 'Permanent Account Number (PAN)',
    confidenceScore: 99.6,
    verificationStatus: 'verified',
    digiLockerIssuer: 'Income Tax Department (CBDT / NSDL)',
    itActSection65BVerified: true,
    summary:
      'Permanent Account Number card issued by Income Tax Department. Validated for direct tax filing and bank KYC compliance.',
    extractedFields: {
      fullName: 'Shivang Khorjuvekar',
      dob: '1995-11-20',
      idNumber: 'ABCDE1234F',
      fatherOrSpouseName: 'Ramesh Khorjuvekar',
      incomeAmount: '₹14,50,000 / annum',
    },
    securityVerification: {
      tamperDetected: false,
      readableQuality: 'High',
      notes: 'Active PAN validated against Income Tax e-Filing database with matching Aadhaar linkage.',
    },
  },
  {
    id: 'doc-itr-03',
    name: 'ITR_V_Acknowledgement_AY2025_26.pdf',
    originalName: 'ITR_V_Acknowledgement_AY2025_26.pdf',
    fileType: 'application/pdf',
    size: 2185400,
    uploadDate: '14 Aug 2026, 14:22 IST',
    isEncrypted: true,
    encryptionAlgorithm: 'AES-256-GCM',
    sha256Hash: '7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
    docType: 'Income Tax Return (ITR-V)',
    confidenceScore: 98.9,
    verificationStatus: 'verified',
    digiLockerIssuer: 'Central Processing Centre, Income Tax Department',
    itActSection65BVerified: true,
    summary:
      'E-verified Income Tax Return Verification for Assessment Year 2025-26 showing total taxable income of ₹14,50,000 with zero pending demand.',
    extractedFields: {
      fullName: 'Shivang Khorjuvekar',
      incomeAmount: '₹14,50,000',
      taxYear: 'AY 2025-26',
      employerOrInstitution: 'Apex Cybernetics India Pvt. Ltd.',
    },
    securityVerification: {
      tamperDetected: false,
      readableQuality: 'High',
      notes: 'E-verified with Aadhaar OTP on 25 July 2025.',
    },
  },
  {
    id: 'doc-udyam-04',
    name: 'MSME_Udyam_Registration_Certificate.pdf',
    originalName: 'MSME_Udyam_Registration_Certificate.pdf',
    fileType: 'application/pdf',
    size: 1650300,
    uploadDate: '15 Aug 2026, 11:05 IST',
    isEncrypted: true,
    encryptionAlgorithm: 'AES-256-GCM',
    sha256Hash: '3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c',
    docType: 'MSME Udyam Registration',
    confidenceScore: 99.2,
    verificationStatus: 'verified',
    digiLockerIssuer: 'Ministry of Micro, Small and Medium Enterprises',
    itActSection65BVerified: true,
    summary:
      'Official Udyam Certificate UDYAM-MH-26-0048921 issued for Software Publishing, Consultancy and Computing Infrastructure services.',
    extractedFields: {
      fullName: 'Shivang Khorjuvekar',
      idNumber: 'UDYAM-MH-26-0048921',
      employerOrBusiness: 'Apex Cybernetics India Pvt. Ltd.',
      qualificationOrCategory: 'Micro Enterprise (NIC Code 6201)',
    },
    securityVerification: {
      tamperDetected: false,
      readableQuality: 'High',
      notes: 'QR code verified against Ministry of MSME national database.',
    },
  },
];

export const DEFAULT_APPLICATIONS: ApplicationRecord[] = [
  {
    id: 'app-sisfs-01',
    title: 'DPIIT Startup India Seed Fund Scheme (SISFS)',
    category: 'Startup & MSME Grant',
    applicationNumber: 'GOI-2026-DPIIT-884920',
    schemeCode: 'DPIIT/SISFS/2026/G-424',
    status: 'In Review',
    submissionDate: '14 Aug 2026, 15:30 IST',
    lastUpdated: '16 Aug 2026 (Scrutiny in Progress)',
    deadline: '15 Nov 2026',
    ministryName: 'Ministry of Commerce and Industry',
    departmentName: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    progressPercentage: 92,
    formTemplateId: 'tmpl-sisfs-grant',
    attachedDocIds: ['doc-aadhaar-01', 'doc-pan-02', 'doc-itr-03', 'doc-udyam-04'],
    formData: {
      applicantName: 'Shivang Khorjuvekar',
      dateOfBirth: '1995-11-20',
      gender: 'Male',
      aadhaarOrPan: 'XXXX-XXXX-8421 / PAN: ABCDE1234F',
      email: 'khorjuvekarshivang@gmail.com',
      phone: '+91 98201 55492',
      primaryAddress: 'Flat 402, Shiv Shristi Enclave, Baner Road',
      cityOrDistrict: 'Pune',
      stateOrUT: 'Maharashtra',
      pincode: '411045',
      citizenshipOrDomicile: 'Citizen of India (Maharashtra Domicile)',
      employerOrBusiness: 'Apex Cybernetics India Pvt. Ltd.',
      annualGrossIncome: '₹14,50,000',
      occupationOrDesignation: 'Founder & Chief Technology Officer',
      schemeOrCategory: 'Early Stage Deep-Tech & AI Startup Prototype Acceleration',
      requestedGrantOrSubsidy: '₹25,00,000 INR (Grant & Convertible Debenture)',
      purposeStatement:
        'Development of high-throughput automated digital citizen identity validation engines and cloud-native cryptographic verifiable credential infrastructures under Make in India.',
      bankAccountNumber: '••••••••8492',
      ifscCode: 'HDFC0000180',
      bankName: 'HDFC Bank, Baner Branch, Pune',
      declarationAccepted: true,
      digitalSignature: 'Shivang Khorjuvekar (Aadhaar e-Signed)',
      dateSigned: '2026-08-14',
    },
    auditReport: {
      readinessScore: 96,
      passedChecks: [
        'Aadhaar e-KYC Identity Verified (UIDAI Level 3 Assurance)',
        'Income Tax PAN linked with Aadhaar and validated against CBDT',
        'DigiLocker ITR-V Gross Income transcript matches declared revenue',
        'MSME Udyam Registration Certificate active and verified',
        'Bank Account NPCI DBT mapper verified for direct electronic subsidy credit',
      ],
      warnings: [],
      recommendations: [
        'Keep prototype demo video link ready for Experts Advisory Committee (EAC) virtual pitch presentation.',
      ],
      verdict: 'Excellent - High Probability of Immediate Scrutiny Clearance',
    },
    timeline: [
      {
        title: 'Application Docket Initialized via MeriPehchaan',
        timestamp: '12 Aug 2026, 10:20 IST',
        description: 'Case opened with DigiLocker verified identity credentials.',
        status: 'completed',
      },
      {
        title: 'DigiLocker Evidentiary Records Linked',
        timestamp: '14 Aug 2026, 14:45 IST',
        description: '4 statutory certificates linked with Section 65B hash seals.',
        status: 'completed',
      },
      {
        title: 'Dossier Transmitted to DPIIT Scrutiny Committee',
        timestamp: '14 Aug 2026, 15:30 IST',
        description: 'Electronic application submitted with Aadhaar e-Sign.',
        status: 'completed',
      },
      {
        title: 'Expert Advisory Committee (EAC) Technical Evaluation',
        timestamp: 'In Progress (Expected 24 Aug 2026)',
        description: 'Stage 2 appraisal by MeitY & DPIIT empanelled domain experts.',
        status: 'current',
      },
      {
        title: 'Final Grant Sanction Order & Seed Fund Disbursement',
        timestamp: 'Upcoming',
        description: 'Direct Bank Transfer (DBT) to registered escrow account.',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'app-dst-02',
    title: 'DST INSPIRE Senior Research Faculty Fellowship',
    category: 'Academic & Research Fellowship',
    applicationNumber: 'GOI-2026-DST-771940',
    schemeCode: 'DST/INSPIRE/2026/F-101',
    status: 'Drafting',
    submissionDate: null,
    lastUpdated: '17 Aug 2026 (Draft Saved)',
    deadline: '30 Nov 2026',
    ministryName: 'Ministry of Science and Technology',
    departmentName: 'Department of Science & Technology (DST)',
    progressPercentage: 80,
    formTemplateId: 'tmpl-dst-inspire',
    attachedDocIds: ['doc-aadhaar-01', 'doc-pan-02'],
    formData: {
      applicantName: 'Shivang Khorjuvekar',
      dateOfBirth: '1995-11-20',
      gender: 'Male',
      aadhaarOrPan: 'XXXX-XXXX-8421 / PAN: ABCDE1234F',
      email: 'khorjuvekarshivang@gmail.com',
      phone: '+91 98201 55492',
      primaryAddress: 'Flat 402, Shiv Shristi Enclave, Baner Road',
      cityOrDistrict: 'Pune',
      stateOrUT: 'Maharashtra',
      pincode: '411045',
      citizenshipOrDomicile: 'Citizen of India (Maharashtra Domicile)',
      employerOrBusiness: 'Indian Institute of Technology / Research Lab',
      annualGrossIncome: '₹14,50,000',
      occupationOrDesignation: 'Postdoctoral Research Associate',
      schemeOrCategory: 'Advanced Computing & Cryptographic Systems Fellowship',
      requestedGrantOrSubsidy: '₹35,00,000 Research Grant + ₹1,25,000/mo Fellowship',
      purposeStatement:
        'Investigating quantum-resistant public key infrastructure and scalable distributed ledger models for sovereign digital governance systems.',
      bankAccountNumber: '••••••••8492',
      ifscCode: 'SBIN0001422',
      bankName: 'State Bank of India, Pune University Campus',
      declarationAccepted: true,
      digitalSignature: 'Shivang Khorjuvekar',
      dateSigned: '2026-08-17',
    },
    timeline: [
      {
        title: 'Statutory Fellowship Draft Created',
        timestamp: '17 Aug 2026, 09:10 IST',
        description: 'Auto-filled personal and domicile details from DigiLocker.',
        status: 'completed',
      },
      {
        title: 'Host Institution Endorsement Upload',
        timestamp: 'Pending Action',
        description: 'Upload signed Annexure-II from university registrar.',
        status: 'current',
      },
      {
        title: 'National Screening Committee Review',
        timestamp: 'Upcoming',
        description: 'Evaluation by DST peer review panel.',
        status: 'upcoming',
      },
    ],
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-init-01',
    role: 'assistant',
    text: `नमस्ते Shivang ji! Welcome to **JanSeva.gov.in** — your official AI Citizen Service Assistant under the Digital India initiative. 🇮🇳

I have synchronized with your **MeriPehchaan (National SSO)** profile and verified your **DigiLocker** repository:
- ✅ **Aadhaar Card (UIDAI)**: Verified e-KYC (Maharashtra Domicile)
- ✅ **Income Tax PAN Card (CBDT)**: Validated & Linked
- ✅ **ITR-V Income Certificate**: Gross Annual Income ₹14,50,000
- ✅ **MSME Udyam Certificate**: UDYAM-MH-26-0048921

How may I assist your statutory application today?
1. Check eligibility for **DPIIT Startup India Seed Fund (₹25 Lakhs Grant)**
2. Auto-fill and print **DST INSPIRE Research Fellowship**
3. Apply for **MSME Capital Subsidy (PMEGP ₹50 Lakhs)**
4. Verify document compliance under **IT Act 2000 Section 65B**`,
    timestamp: 'Just now',
    suggestions: [
      'Am I eligible for ₹25 Lakhs DPIIT Startup Seed Fund?',
      'Auto-fill DST INSPIRE Fellowship form from DigiLocker',
      'Explain PMEGP 35% government subsidy scheme',
      'Run pre-submission compliance audit score',
    ],
  },
];
